theme = "gruvbox_dark_hard"

[editor]
line-number = "absolute"
scrolloff=0
mouse = false
cursorline=true
auto-completion=true
true-color=true
color-modes=true
#bufferline="always"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"             # Use a thin bar | in insert mode
normal = "block"           # Use a block █ in normal mode
select = "underline"       # Use an underline _ in selection mode

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]

[keys.normal]
C-e = [
":sh rm -f /tmp/helix-yazi",
    # Use 'insert-output' instead of 'tmux popup'
    # We use '.' to open the current folder safely
    ":insert-output yazi . --chooser-file=/tmp/helix-yazi",
    ":open %sh{test -f /tmp/helix-yazi && cat /tmp/helix-yazi}",
    ":redraw"
]
