
# Font file
include fonts.conf

# Appearance file
include appearance.conf


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include ./themes/catppuccin-Mocha.conf
# include ./themes/rose-pine.conf
# include ./themes/tokyo-night.conf
# include ./themes/rose-pine.conf
# include ./themes/gruve-box-dark-hard.conf
# END_KITTY_THEME
