# ========================
# Plugin Manager
# ========================
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
# Uncomment if you want the Dracula theme
# set -g @plugin 'dracula/tmux'


set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-kitty:Ss=\E[%p1%d q:Se=\E[2 q'
set -as terminal-overrides ',xterm-kitty:cnorm=\033[?12h\033[?25h'
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# set -g status-style 'bg=#${config.colorScheme.palette.base00}'
set -g base-index 1

setw -g mode-keys vi
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# bind -r D neww -c "#{pane_current_path}" "[[ -e README.md ]] && nvim README.md || nvim ~/personal/todo.md"

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww tmux-sessionizer.sh"
# bind-key -r g run-shell "tmux neww git-sessionizer"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# create a new tmux session
# bind-key -r n command-prompt -p "New session name: " "new-session -s '%%'"

bind k confirm kill-window # kill current window
bind K confirm kill-server # kill all session (exit tmux)
bind x confirm kill-session # kill current session

# Initialize TPM (must be at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
